<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Template Name: Archive
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

//* Remove standard post content output
remove_action( 'genesis_post_content', 'genesis_do_post_content' );
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );

add_action( 'genesis_entry_content', 'genesis_page_archive_content' );
add_action( 'genesis_post_content', 'genesis_page_archive_content' );
/**
 * This function outputs sitemap-esque columns displaying all pages,
 * categories, and recent posts.
 *
 * @since 1.6
 */
function genesis_page_archive_content() { ?>

    <h4><?php _e( 'Pages:', 'genesis' ); ?></h4>
    <ul>
		<?php wp_list_pages( 'title_li=' ); ?>
    </ul>

    <h4><?php _e( 'News:', 'genesis' ); ?></h4>
    <ul>
		<?php wp_get_archives( 'type=postbypost&limit=100' ); ?>
    </ul>

    <!--	<h4>--><?php //_e( 'News:', 'genesis' ); ?><!--</h4>-->
    <!--	<ul>-->
    <!--		--><?php //wp_list_categories( 'taxonomy=news' ); ?>
    <!--	</ul>-->


	<?php
}

// Exclude certain pages from page_archive.php
function filter_wp_list_pages_excludes( $exclude_array ) {
	return array_merge( $exclude_array, array(45, 1164, 1167, 1174, 1183, 1187, 1205, 1216 ) );
}
genesis();
